#!/usr/bin/env node

import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { format } from 'prettier';

import {
  directoryNames,
  isMain,
  parseCliArguments,
  readJson,
} from './lib/artifacts.mjs';

const scriptRoot = path.dirname(fileURLToPath(import.meta.url));
const repositoryRoot = path.resolve(scriptRoot, '..');

async function humanCatalog(plugins) {
  const lines = [
    '# Artifact Catalog',
    '',
    'This file is generated by `npm run catalog`. Do not edit it by hand.',
    '',
    '## Portable Skills',
    '',
    'Portable Skills are discovered directly from `skills/` during generation.',
    '',
    '## Plugins',
    '',
    '| Plugin | Claude Code | Codex | Version |',
    '| --- | --- | --- | --- |',
  ];
  if (plugins.length === 0) {
    lines.push('| _None yet_ | — | — | — |');
  } else {
    for (const plugin of plugins) {
      lines.push(
        `| ${plugin.name} | ${plugin.claude ? 'Yes' : 'No'} | ${plugin.codex ? 'Yes' : 'No'} | ${plugin.version} |`,
      );
    }
  }
  return format(`${lines.join('\n')}\n`, {
    parser: 'markdown',
    proseWrap: 'preserve',
  });
}

export async function renderCatalogs(root = repositoryRoot) {
  const plugins = [];
  for (const name of await directoryNames(path.join(root, 'plugins'))) {
    const pluginRoot = path.join(root, 'plugins', name);
    const claudeManifest = await readJson(
      path.join(pluginRoot, '.claude-plugin', 'plugin.json'),
    );
    const codexManifest = await readJson(
      path.join(pluginRoot, '.codex-plugin', 'plugin.json'),
    );
    if (!claudeManifest && !codexManifest) continue;
    plugins.push({
      name,
      claude: claudeManifest,
      codex: codexManifest,
      version: claudeManifest?.version ?? codexManifest.version,
    });
  }

  plugins.sort((left, right) => left.name.localeCompare(right.name));

  const claude = {
    name: 'ergouzi-agent-skills',
    owner: { name: 'Aiman Labs' },
    metadata: {
      description: 'Public Claude Code plugins from Ergouzi Agent Skills.',
    },
    plugins: plugins
      .filter((plugin) => plugin.claude)
      .map((plugin) => ({
        name: plugin.name,
        source: `./plugins/${plugin.name}`,
        description: plugin.claude.description,
        version: plugin.claude.version,
        author: plugin.claude.author,
        homepage: plugin.claude.homepage,
        repository: plugin.claude.repository,
        license: plugin.claude.license,
        keywords: plugin.claude.keywords,
      })),
  };

  const codex = {
    name: 'ergouzi-agent-skills',
    interface: { displayName: 'Ergouzi Agent Skills' },
    plugins: plugins
      .filter((plugin) => plugin.codex)
      .map((plugin) => ({
        name: plugin.name,
        source: { source: 'local', path: `./plugins/${plugin.name}` },
        policy: { installation: 'AVAILABLE', authentication: 'ON_INSTALL' },
        category: plugin.codex.interface.category,
      })),
  };

  return { claude, codex, human: await humanCatalog(plugins), plugins };
}

async function formatGeneratedJson(value) {
  return format(JSON.stringify(value, null, 2), { parser: 'json' });
}

async function expectedFiles(root, rendered) {
  return [
    {
      path: path.join(root, '.claude-plugin', 'marketplace.json'),
      content: await formatGeneratedJson(rendered.claude),
    },
    {
      path: path.join(root, '.agents', 'plugins', 'marketplace.json'),
      content: await formatGeneratedJson(rendered.codex),
    },
    { path: path.join(root, 'docs', 'catalog.md'), content: rendered.human },
  ];
}

export async function writeCatalogs(root = repositoryRoot) {
  const rendered = await renderCatalogs(root);
  for (const file of await expectedFiles(root, rendered)) {
    await fs.mkdir(path.dirname(file.path), { recursive: true });
    await fs.writeFile(file.path, file.content);
  }
  return rendered;
}

export async function checkCatalogs(root = repositoryRoot) {
  const rendered = await renderCatalogs(root);
  const errors = [];
  for (const file of await expectedFiles(root, rendered)) {
    let actual;
    try {
      actual = await fs.readFile(file.path, 'utf8');
    } catch (error) {
      if (error.code === 'ENOENT') {
        errors.push(
          `Generated catalog is missing: ${path.relative(root, file.path)}`,
        );
        continue;
      }
      throw error;
    }
    if (actual !== file.content) {
      errors.push(
        `Generated catalog is out of date: ${path.relative(root, file.path)}`,
      );
    }
  }
  return errors;
}

async function main() {
  const { flags } = parseCliArguments(process.argv.slice(2));
  if (flags.has('check')) {
    const errors = await checkCatalogs();
    if (errors.length > 0) {
      for (const error of errors) console.error(error);
      process.exitCode = 1;
      return;
    }
    console.log('Catalogs are up to date.');
    return;
  }
  const rendered = await writeCatalogs();
  console.log(
    `Generated catalogs for ${rendered.plugins.length} plugin${rendered.plugins.length === 1 ? '' : 's'}.`,
  );
}

if (isMain(import.meta.url)) {
  main().catch((error) => {
    console.error(`generate-catalog: ${error.message}`);
    process.exitCode = 1;
  });
}
